module finfolio {
    requires javafx.controls;
    requires javafx.fxml;
    requires de.jensd.fx.glyphs.fontawesome;
    requires org.controlsfx.controls;
    requires org.kordamp.bootstrapfx.core;
    requires java.sql;
    requires javafx.graphics;
    requires java.mail;
    requires twilio;
    requires activation;
    requires com.google.zxing;
    requires com.google.zxing.javase;
    requires org.apache.poi.poi;
    requires org.apache.poi.ooxml;
    requires java.desktop;
    //requires com.google.gson;
    requires okhttp3;
    requires kernel;
    requires layout;
    requires io;
    requires javafx.web;
    requires com.google.gson;
    opens com.example.finfolio.Investissement.Controller to javafx.fxml;
    exports com.example.finfolio.Investissement.Controller;
    opens com.example.finfolio.Investissement.Entite to javafx.base;
    exports com.example.finfolio.Investissement;
    opens com.example.finfolio.Investissement to javafx.fxml;

    opens com.example.finfolio to javafx.fxml;
    exports com.example.finfolio;
    exports com.example.finfolio.UsrController;
    opens com.example.finfolio.UsrController to javafx.fxml;
    exports com.example.finfolio.Admin;
    opens com.example.finfolio.Admin to javafx.fxml;
    opens com.example.finfolio.User to javafx.fxml;
    exports com.example.finfolio.Service;
    opens com.example.finfolio.Service to javafx.fxml;
    exports com.example.finfolio.Entite;
    opens com.example.finfolio.Entite to javafx.fxml;
    exports com.example.finfolio.util;
    opens com.example.finfolio.util to javafx.fxml;
    exports com.example.finfolio.Depense;
    opens com.example.finfolio.Depense to javafx.fxml;
    exports com.example.finfolio.Evenement;
    opens com.example.finfolio.Evenement to javafx.fxml;

    exports com.example.finfolio.Credits;
    opens com.example.finfolio.Credits to javafx.fxml;
    exports com.example.finfolio.Portfolio;
    opens com.example.finfolio.Portfolio to javafx.fxml;
    exports com.example.finfolio.Portfolio.Controller.ActifsNonCourants to  javafx.fxml;
    opens com.example.finfolio.Portfolio.Controller.ActifsNonCourants to  javafx.fxml;
    exports  com.example.finfolio.Portfolio.Controller.ActifsCourants to  javafx.fxml;
    opens com.example.finfolio.Portfolio.Controller.ActifsCourants to  javafx.fxml;
    opens  com.example.finfolio.Portfolio.Entite to javafx.base;
}
